<?php
$translate = $this->plugin('translate');
$this->headLink()->prependStylesheet($this->assetUrl('css/resource-page-blocks.css', 'Omeka'));
$this->htmlElement('body')->appendAttribute('class', 'item resource show');
$filterLocale = (bool) $this->siteSetting('filter_locale_values');
$lang = $this->lang();
?>
<?php echo $this->pageTitle($item->displayTitle(null, ($filterLocale ? $lang : null)), 2); ?>
<h3><?php echo $translate('Item'); ?></h3>
<div class="full-width">
<?php echo $this->resourcePageBlocks($item, 'full_width_main')->getBlocks(); ?>
</div>

<div class="with-sidebar">
<?php $this->trigger('view.show.before'); ?>
<?php echo $this->resourcePageBlocks($item)->getBlocks(); ?>
<?php $this->trigger('view.show.after'); ?>
</div>

<div class="sidebar right">
    <?php echo $this->resourcePageBlocks($item, 'right')->getBlocks(); ?>
</div>
