<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\MediaRepresentation $resource
 * @var \Omeka\Api\Representation\MediaRepresentation $media
 * @var array $options
 */

// User attribute names and values are already escaped.
$attrs = '';
foreach ($options['attributes'] as $name => $value) $attrs .= ' ' . $name . '="' . $value . '"';
?>

<iframe<?= $attrs ?>></iframe>
